// Turning a pitch class into a chord symbol a musician recognises.
//
// Sounds trivial and is not. Pitch class 10 is A# in B major and Bb in F major,
// and they are not interchangeable to a reader: a chart that says A# in a flat
// key looks like it was generated by a machine that does not know what key the
// song is in — which it is, unless it estimates one. Getting this right is a
// small amount of code and the single most noticeable "someone who plays music
// made this" detail in the whole panel.
(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.InstrufiltChordFormat = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const SHARP = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
  const FLAT  = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"];

  // Position on the circle of fifths for each MAJOR key, negative = flat side.
  // F# major is written with 6 sharps; Gb with 6 flats — both appear, and
  // either is defensible, so it follows the sharp side by convention.
  const FIFTHS_MAJOR = {
    0: 0,    // C
    7: 1,    // G
    2: 2,    // D
    9: 3,    // A
    4: 4,    // E
    11: 5,   // B
    6: 6,    // F#
    1: -5,   // Db
    8: -4,   // Ab
    3: -3,   // Eb
    10: -2,  // Bb
    5: -1,   // F
  };

  // Krumhansl-Schmuckler key profiles: how strongly each scale degree is
  // weighted in music of that mode. Correlating an aggregate chromagram against
  // all 24 rotations is the standard cheap key estimator.
  const KS_MAJOR = [6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88];
  const KS_MINOR = [6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17];

  /**
   * Whether a key is written with flats.
   * @param {number|null} keyPc  tonic pitch class
   * @param {"maj"|"min"} keyMode
   */
  function usesFlats(keyPc, keyMode) {
    if (keyPc === null || keyPc === undefined) return false;
    // A minor key is spelled like its relative major (A minor <-> C major).
    const majorPc = keyMode === "min" ? (keyPc + 3) % 12 : keyPc;
    const f = FIFTHS_MAJOR[majorPc];
    return f !== undefined && f < 0;
  }

  /**
   * Pitch class -> note name.
   * @param {number} pc
   * @param {{keyPc?:number, keyMode?:string, prefer?:"sharp"|"flat"}} [ctx]
   */
  function noteName(pc, ctx) {
    const i = ((pc % 12) + 12) % 12;
    if (ctx && ctx.prefer === "flat") return FLAT[i];
    if (ctx && ctx.prefer === "sharp") return SHARP[i];
    return usesFlats(ctx && ctx.keyPc, ctx && ctx.keyMode) ? FLAT[i] : SHARP[i];
  }

  /**
   * A chord symbol: "C", "Am", "Bb", "F#m" — and, when the chord carries the
   * optional fields a verified external chart provides, "Gm7", "Dsus4",
   * "Eb/Ab". The local detector only emits {root, quality}; `ext` and `bass`
   * exist so richer data does not have to be flattened to triads on the way in.
   * @param {{root:number, quality:number, ext?:string, bass?:number}} chord
   *        quality 0 major, 1 minor
   */
  function chordName(chord, ctx) {
    if (!chord || chord.root === undefined || chord.root < 0) return "N.C.";
    let name = noteName(chord.root, ctx) + (chord.quality === 1 ? "m" : "");
    if (chord.ext) name += chord.ext;
    if (typeof chord.bass === "number" && chord.bass >= 0 && chord.bass % 12 !== chord.root % 12) {
      name += "/" + noteName(chord.bass, ctx);
    }
    return name;
  }

  /**
   * Note name -> pitch class. "C" 0, "F#" 6, "Bb" 10; null when unparseable.
   * Accidentals stack ("Cbb" is 10) because double flats do appear in the wild.
   */
  const NATURAL_PC = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };
  function noteToPc(name) {
    if (typeof name !== "string" || !name.length) return null;
    let pc = NATURAL_PC[name[0].toUpperCase()];
    if (pc === undefined) return null;
    for (const ch of name.slice(1)) {
      if (ch === "#") pc++;
      else if (ch === "b") pc--;
      else return null;
    }
    return ((pc % 12) + 12) % 12;
  }

  /**
   * Estimate key from an aggregate chromagram.
   * @param {number[]} chroma  12 weights
   * @returns {{pc:number, mode:"maj"|"min", confidence:number}}
   */
  function estimateKey(chroma) {
    if (!chroma || chroma.length !== 12) return { pc: 0, mode: "maj", confidence: 0 };

    let best = -Infinity, second = -Infinity, bestPc = 0, bestMode = "maj";
    for (const [profile, mode] of [[KS_MAJOR, "maj"], [KS_MINOR, "min"]]) {
      for (let r = 0; r < 12; r++) {
        const rotated = [];
        for (let i = 0; i < 12; i++) rotated.push(chroma[(r + i) % 12]);
        const c = correlate(rotated, profile);
        if (c > best) { second = best; best = c; bestPc = r; bestMode = mode; }
        else if (c > second) second = c;
      }
    }

    const margin = best - second;
    return { pc: bestPc, mode: bestMode, confidence: margin / (margin + 0.15) };
  }

  function correlate(a, b) {
    let ma = 0, mb = 0;
    for (let i = 0; i < 12; i++) { ma += a[i]; mb += b[i]; }
    ma /= 12; mb /= 12;
    let num = 0, da = 0, db = 0;
    for (let i = 0; i < 12; i++) {
      const x = a[i] - ma, y = b[i] - mb;
      num += x * y; da += x * x; db += y * y;
    }
    const den = Math.sqrt(da * db);
    return den > 1e-12 ? num / den : 0;
  }

  function keyName(key, ctx) {
    if (!key) return "";
    const prefer = usesFlats(key.pc, key.mode) ? "flat" : "sharp";
    return noteName(key.pc, { prefer }) + (key.mode === "min" ? " minor" : " major");
  }

  /**
   * Transpose a chord by semitones. Display-only — nothing about the audio
   * changes, so this is what a capo'd guitarist reads rather than a re-analysis.
   */
  function transposeChord(chord, semitones) {
    if (!chord || chord.root < 0) return chord;
    const moved = { ...chord, root: (((chord.root + semitones) % 12) + 12) % 12 };
    // A slash chord's bass moves with it, or "capo 2" would relabel the chord
    // and leave the bass note behind.
    if (typeof chord.bass === "number" && chord.bass >= 0) {
      moved.bass = (((chord.bass + semitones) % 12) + 12) % 12;
    }
    return moved;
  }

  function transposeKey(key, semitones) {
    if (!key) return key;
    return { ...key, pc: (((key.pc + semitones) % 12) + 12) % 12 };
  }

  /**
   * Capo position -> the transpose a guitarist needs.
   *
   * Clamping a capo at the octave: past fret 11 the shapes repeat, and a chart
   * asking for capo 14 is a chart nobody can play.
   */
  function capoTranspose(fret) {
    const f = Math.max(0, Math.min(11, fret | 0));
    // capo N raises the instrument, so the read chord drops N. The explicit
    // zero avoids -0, which is a distinct value to Object.is and serialises
    // as "-0" into the cached chart.
    return f === 0 ? 0 : -f;
  }

  /** Format a whole chart's worth of chords, once, in key context. */
  function labelChart(chords, opts) {
    const semitones = (opts && opts.transpose) || 0;
    const key = opts && opts.key
      ? transposeKey(opts.key, semitones)
      : null;
    const ctx = {
      keyPc: key ? key.pc : undefined,
      keyMode: key ? key.mode : undefined,
      prefer: opts && opts.prefer,
    };
    return (chords || []).map((c) => {
      const moved = transposeChord(c, semitones);
      return { ...moved, label: chordName(moved, ctx) };
    });
  }

  return {
    noteName, noteToPc, chordName, estimateKey, keyName,
    transposeChord, transposeKey, capoTranspose, labelChart, usesFlats,
    SHARP, FLAT, KS_MAJOR, KS_MINOR,
  };
});
